connector.name=hive
hive.metastore.uri=thrift://hadoop2428:9083
hive.config.resources=/opt/module/hadoop-3.3.6/etc/hadoop/core-site.xml,/opt/module/hadoop-3.3.6/etc/hadoop/hdfs-site.xml
hive.allow-drop-table=true
hive.allow-rename-table=true
hive.metastore-cache-ttl=0s
hive.metastore-refresh-interval=1s
hive.parquet.time-zone=Asia/Shanghai
